MERGE INTO USER_BANCU.KATALOG_45_1063 T
USING (
 SELECT 
    B.CUIIO AS STRING_CUIIO, 
    A.IDNO  AS SUBSTRING_IDNO,
    B.IDNO  AS  STRING_IDNO,
    A.DENUMIRE AS SUBSTRING_DENUMIRE,
    B.DENUMIRE AS STRING_DENUMIRE 
FROM 
    USER_BANCU.KATALOG_45_1063 A
JOIN 
    USER_BANCU.KATALOG_45_1063 B
ON 
    A.CUIIO <> B.CUIIO
    AND TO_CHAR(B.CUIIO) LIKE TO_CHAR(A.CUIIO) || '%'
) S
ON (T.CUIIO = S.STRING_CUIIO)
WHEN MATCHED THEN 
    UPDATE SET T.IDNO = S.SUBSTRING_IDNO,
    T.DENUMIRE =  S.SUBSTRING_DENUMIRE
    ;
