--DROP TABLE USER_BANCU.KATALOG_45_1063_24 CASCADE CONSTRAINTS;
--ORDINE	CUIIO	PARENT_CUIIO	DENUMIRE	CUATM	PARENT_CUATM	CFP	CFOJ	CAEM2	IDNO	COL1

CREATE TABLE USER_BANCU.KATALOG_45_1063_24_FINAL
(
  ORDINE        NUMBER,
  CUIIO         NUMBER,
  PARENT_CUIIO  NUMBER,
 -- CUIIO_VERS    NUMBER,
  DENUMIRE      VARCHAR2(1024 BYTE),
  CUATM         VARCHAR2(1024 BYTE),
  PARENT_CUATM  VARCHAR2(1024 BYTE),
  CFP           VARCHAR2(1024 BYTE),
  CFOJ          VARCHAR2(1024 BYTE),
  CAEM2         VARCHAR2(1024 BYTE),
  IDNO          VARCHAR2(1024 BYTE),
  COL1          NUMBER
  
)
TABLESPACE TBS_DTI_USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;
