SELECT 
D.CUIIO,
D.CUIIO_VERS,
SUM(D.COL1) AS COL1


FROM
  VW_DATA_ALL D
  INNER JOIN RENIM R1 ON (D.CUIIO=R1.CUIIO AND D.CUIIO_VERS=R1.CUIIO_VERS)
WHERE
  D.PERIOADA IN (:pPERIOADA) AND
  D.FORM IN (:pFORM) AND 
  D.capitol=399
  AND D.RIND IN ('2000')
--  AND D.CUIIO IN (38670189602,3867018)
  
  
  GROUP BY
  D.CUIIO,
  D.CUIIO_VERS